require_relative "backpack_connect/assertions/alignment_object"
require_relative "backpack_connect/assertions/badge_assertion"
require_relative "backpack_connect/assertions/badge_class"
require_relative "backpack_connect/assertions/identity_object"
require_relative "backpack_connect/assertions/issuer_organization"
require_relative "backpack_connect/assertions/verification_object"
require_relative "backpack_connect/authenticator"
require_relative "backpack_connect/api"

module BackpackConnect
end
